### ISSUE TITLE
dlaczego przyjmujesz 🍆 jako poprawną nazwę?

### ISSUE THREAD

**Issue by gavjan** [jmolinski/ipp-2020-testy#10]
test hb_5

**Comment by gavjan** [comment]
test hb_5

**Comment by jmolinski** [comment]
ta linija i hexowe kody kolejnych znakow z tej linijki

`ADD 🍆 a`
`41 44 44 20 F0 9F 8D 86 20 61 0A`

wszystkie znaki sa z zakresu 33-255 (21-FF hex) lub sa znakami bialymi
w poleceniu nie ma zadnego zapisu ktory stanowilby, ze ten input jest nieprawidlowy, zatem jest prawidlowy

**Comment by jmolinski** [comment]
rozumiem ze akceptujesz to uzasadnienie wiec zamykam
